import test from 'node:test';
import assert from 'node:assert/strict';
import { runAgentOrchestrator } from './orchestrator.js';
import { OpenAiCompatibleModelProvider } from './openai-compatible.js';
import type { ConversationSnapshot,ModelProvider,RunStorePort,ToolExecutorPort } from './ports.js';
const snapshot:ConversationSnapshot={organizationId:'org',conversationId:'conv',customerId:'customer',mode:'AI_ACTIVE',ownershipEpoch:0,leaseOwner:'w',leaseFence:1,nextIngressSequence:2,processedSequence:0,targetIngressSequence:1,messages:[{id:'in',direction:'INBOUND',ingressSequence:1,timelineSequence:1,contentText:'synthetic fault fixture'}],summaryText:null,summaryWatermark:null,agentConfigVersionId:'cfg',promptVersion:'test',modelProfile:'injected-adversarial-fault',toolAllowlist:['searchServices','getServicePrice','getActiveOffers','getEffectivePolicy','searchKnowledge','getAvailableSlots','createBooking']};
function fixture(decisions:unknown[]){let i=0,executions=0,mutations=0,finalizations=0;const records:unknown[]=[];
 const provider:ModelProvider={id:'injected-adversarial-fault',async generate(){const d=decisions[Math.min(i++,decisions.length-1)];if(d instanceof Error)throw d;return {decision:d,finishReason:'stop',usage:{estimated:true},providerRequestId:`injected-${i}`,model:'injected-adversarial-fault'};}};
 const store:RunStorePort={async createOrResumeRun(){return {agentRunId:'injected-run',status:'RUNNING',resumed:false};},async loadAuthority(){return {mode:'AI_ACTIVE',ownershipEpoch:0,leaseOwner:'w',leaseFence:1,nextIngressSequence:2,processedSequence:0};},async hasNewerInbound(){return false;},async recordToolCall(x){records.push(x);},async claimCommand(){return {alreadySucceeded:false,resultJson:null,operationId:'operation'};},async completeCommand(){},async finalizeSuccess(){finalizations++;return {outboundMessageId:'injected-out'};},async finalizeHandoff(){return {newEpoch:1};},async finalizeTerminal(){},async recordUsage(){}};
 const tools:ToolExecutorPort={listTools(){return snapshot.toolAllowlist.map(name=>({name,version:'1',description:'injected fixture tool',classification:name==='createBooking'?'mutate' as const:'read' as const,inputSchema:{type:'object'}}));},async execute(name){executions++;if(name==='createBooking'){mutations++;return {ok:true,code:'OK',data:{bookingId:'backend-booking'}};}return {ok:true,code:'OK',data:{evidenceRef:'backend-read',slots:[],amountMinor:'50000',currency:'IQD'}};}};
 return {provider,store,tools,allowFakeProvider:false,counts:()=>({calls:i,executions,mutations,finalizations,records})};}
const request=(toolName:string,n=0)=>({type:'tool_request',toolName,arguments:{query:`q-${n}`,slotToken:'injected-backend-token'}});
const final={type:'final_response',text:'No confirmed availability.',claims:[]};
for(const [name,invalid] of Object.entries({prose:'plain prose',unknownFields:{type:'tool_request',toolName:'createBooking',arguments:{},extra:true},missingType:{toolName:'createBooking',arguments:{}},untypedFinal:{text:'untyped reply',claims:[]},missingArguments:{type:'tool_request',toolName:'createBooking'},malformedClaims:{type:'final_response',text:'bad',claims:[{kind:'invalid'}]}}))test(`MALFORMED_MODEL_OUTPUT_SAFETY ${name}`,async()=>{const f=fixture([invalid,invalid,request('createBooking')]);const r=await runAgentOrchestrator(snapshot,f);assert.equal(r.terminal,'FAILED');assert.equal(f.counts().calls,2);assert.equal(f.counts().executions,0);assert.equal(f.counts().mutations,0);});
test('MALFORMED_MODEL_OUTPUT_SAFETY unknown tool never executes',async()=>{const f=fixture([request('notAllowed')]);const r=await runAgentOrchestrator(snapshot,f);assert.equal(r.reason,'tool_not_found');assert.equal(f.counts().executions,0);});
test('MALFORMED_MODEL_OUTPUT_SAFETY reserve cannot execute tool or mutation',async()=>{const f=fixture([...Array.from({length:5},(_,i)=>request('searchServices',i)),request('createBooking')]);const r=await runAgentOrchestrator(snapshot,f);assert.equal(r.reason,'finalization_reserve_tool_request');assert.equal(f.counts().calls,6);assert.equal(f.counts().mutations,0);});
test('TOOL_LOOP_GUARD identical normalized input stops before third execution',async()=>{const f=fixture([request('searchServices')]);const r=await runAgentOrchestrator(snapshot,f);assert.equal(r.reason,'repeated_identical_tool');assert.equal(f.counts().executions,2);});
test('TOOL_LOOP_GUARD different normalized inputs remain legitimate',async()=>{const f=fixture([request('searchServices',1),request('searchServices',2),final]);const r=await runAgentOrchestrator(snapshot,f);assert.equal(r.terminal,'SUCCEEDED');assert.equal(f.counts().executions,2);});
for(const flow of ['getServicePrice','getActiveOffers','searchKnowledge','getAvailableSlots','getEffectivePolicy'])for(const fault of ['429','503','timeout','malformed','safe_stop'])test(`DEEPSEEK_BUSINESS_FAILURE_RECOVERY injected ${flow} ${fault}`,async()=>{
 const output=fault==='malformed'?{type:'bad'}:fault==='safe_stop'?{type:'safe_stop',reason:'injected_safe_stop'}:Object.assign(new Error(`injected_${fault}`),{retryable:true});const f=fixture([request(flow),output]);const r=await runAgentOrchestrator(snapshot,f);assert.notEqual(r.terminal,'SUCCEEDED');assert.equal(f.counts().mutations,0);assert.ok(f.counts().calls<=6);assert.equal(f.counts().executions,1);
});
for(const fault of ['429','503','timeout','malformed','safe_stop'])test(`DEEPSEEK_BUSINESS_FAILURE_RECOVERY injected post-mutation ${fault}`,async()=>{const output=fault==='malformed'?{type:'bad'}:fault==='safe_stop'?{type:'safe_stop',reason:'unparseable_provider_json'}:Object.assign(new Error(`injected_${fault}`),{retryable:true});const f=fixture([request('createBooking'),output]);const r=await runAgentOrchestrator(snapshot,f);assert.equal(f.counts().mutations,1);assert.ok(f.counts().calls<=6);if(['malformed','safe_stop'].includes(fault)){assert.equal(r.terminal,'SUCCEEDED');assert.equal(r.finalization?.source,'AUTHORITATIVE_TOOL_RESULT');assert.equal(f.counts().finalizations,1);}else assert.notEqual(r.terminal,'SUCCEEDED');});
for(const status of [429,503])test(`DEEPSEEK_ADAPTER_HTTP injected ${status}`,async()=>{let calls=0;const provider=new OpenAiCompatibleModelProvider({apiKey:'synthetic-fault-fixture',model:'deepseek-chat',baseUrl:'http://127.0.0.1:9',fetchImpl:async()=>{calls++;return new Response('{}',{status});}});await assert.rejects(()=>provider.generate({messages:[],tools:[],responseSchemaHint:'AgentDecision',budget:{},deadlineMs:100,traceContext:{}}),(e:any)=>e.retryable===true);assert.equal(calls,1);});
test('DEEPSEEK_ADAPTER_TIMEOUT injected transport cancellation is bounded',async()=>{const provider=new OpenAiCompatibleModelProvider({apiKey:'synthetic-fault-fixture',model:'deepseek-chat',baseUrl:'http://127.0.0.1:9',fetchImpl:async(_url,input)=>new Promise((_resolve,reject)=>input?.signal?.addEventListener('abort',()=>reject(new Error('injected_abort'))))});await assert.rejects(()=>provider.generate({messages:[],tools:[],responseSchemaHint:'AgentDecision',budget:{},deadlineMs:10,traceContext:{}}),(e:any)=>e.retryable===true);});
test('DEEPSEEK_ADAPTER_MALFORMED injected prose performs exactly one repair then fails closed',async()=>{let calls=0;const provider=new OpenAiCompatibleModelProvider({apiKey:'synthetic-fault-fixture',model:'deepseek-chat',baseUrl:'http://127.0.0.1:9',fetchImpl:async()=>{calls++;return Response.json({choices:[{message:{content:'unstructured prose'}}]});}});const r=await provider.generate({messages:[],tools:[],responseSchemaHint:'AgentDecision',budget:{},deadlineMs:100,traceContext:{}});assert.deepEqual(r.decision,{type:'safe_stop',reason:'unparseable_provider_json'});assert.equal(calls,2);});

for(const [flow,names] of Object.entries({priceOffer:['getServicePrice','getActiveOffers'],topicResume:['getAvailableSlots','getActiveOffers','searchKnowledge'],multiIntent:['searchServices','getServicePrice','getActiveOffers','getAvailableSlots']}))for(const fault of ['429','503','timeout','malformed','safe_stop'])test(`DEEPSEEK_BUSINESS_FAILURE_RECOVERY injected ${flow} ${fault}`,async()=>{const output=fault==='malformed'?{type:'bad'}:fault==='safe_stop'?{type:'safe_stop',reason:'injected_safe_stop'}:Object.assign(new Error(`injected_${fault}`),{retryable:true});const f=fixture([...names.map((n,i)=>request(n,i)),output]);const r=await runAgentOrchestrator(snapshot,f);assert.notEqual(r.terminal,'SUCCEEDED');assert.equal(f.counts().mutations,0);assert.ok(f.counts().calls<=6);assert.equal(f.counts().executions,names.length);});

test('crash resume restores budget and continues tool ordinals without replay collision',async()=>{const f=fixture([request('getServicePrice'),final]);f.store.createOrResumeRun=async()=>({agentRunId:'injected-run',status:'RUNNING',resumed:true,priorModelCalls:3,priorToolCalls:2});const result=await runAgentOrchestrator(snapshot,f);assert.equal(result.terminal,'SUCCEEDED');assert.equal(f.counts().calls,2);assert.equal((f.counts().records[0] as any).ordinal,3);});
test('crash resume cannot reset an exhausted model budget',async()=>{const f=fixture([request('createBooking')]);f.store.createOrResumeRun=async()=>({agentRunId:'injected-run',status:'RUNNING',resumed:true,priorModelCalls:6,priorToolCalls:3});const result=await runAgentOrchestrator(snapshot,f);assert.equal(result.terminal,'BUDGET_EXCEEDED');assert.equal(f.counts().calls,0);assert.equal(f.counts().mutations,0);});
test('crash resume uses durable booking success without a second mutation',async()=>{const f=fixture([request('createBooking')]);f.store.createOrResumeRun=async()=>({agentRunId:'injected-run',status:'RUNNING',resumed:true,priorModelCalls:1,priorToolCalls:1,successfulBookingResult:{bookingId:'durable-booking'}});const result=await runAgentOrchestrator(snapshot,f);assert.equal(result.terminal,'SUCCEEDED');assert.equal(result.finalization?.source,'AUTHORITATIVE_TOOL_RESULT');assert.equal(f.counts().calls,0);assert.equal(f.counts().executions,0);assert.equal(f.counts().finalizations,1);});
test('crash resume restores the identical-tool loop guard',async()=>{const {hashNormalizedArgs}=await import('./run-key.js');const d=request('searchServices');const f=fixture([d]);f.store.createOrResumeRun=async()=>({agentRunId:'injected-run',status:'RUNNING',resumed:true,priorModelCalls:2,priorToolCalls:2,priorToolFingerprints:[{toolName:d.toolName,argsHash:hashNormalizedArgs(d.arguments),count:2}]});const result=await runAgentOrchestrator(snapshot,f);assert.equal(result.reason,'repeated_identical_tool');assert.equal(f.counts().executions,0);});

test('rapid-fire context ends with the exact target inbound even when an older assistant reply is appended later',async()=>{const {buildContextMessages}=await import('./context-builder.js');const messages=Array.from({length:20},(_,i)=>({id:`in-${i}`,direction:'INBOUND' as const,ingressSequence:i+1,timelineSequence:i+1,contentText:i===19?'current service price inquiry':`older waiting message ${i}`}));const snap={...snapshot,targetIngressSequence:20,messages:[...messages,{id:'late-out',direction:'OUTBOUND' as const,ingressSequence:null,timelineSequence:21,contentText:'older turn acknowledgment'}]};const built=buildContextMessages(snap);assert.equal(built.at(-1)?.role,'user');assert.ok(built.at(-1)?.content.endsWith('current service price inquiry'));assert.equal(built.filter(m=>m.content.includes('current service price inquiry')).length,1);});

 test('explicit offers detour cannot finalize without offers evidence and correction remains bounded',async()=>{const snap={...snapshot,messages:[{...snapshot.messages[0],contentText:'قبل لا أختار، شنو عروضكم؟'}]};const f=fixture([final,{type:'tool_request',toolName:'getActiveOffers',arguments:{}},final]);const r=await runAgentOrchestrator(snap,f);assert.equal(r.terminal,'SUCCEEDED');assert.equal(f.counts().calls,3);assert.equal(f.counts().executions,1);assert.equal(f.counts().mutations,0);const bad=fixture([final,final]);const stopped=await runAgentOrchestrator(snap,bad);assert.equal(stopped.reason,'required_offers_evidence_missing');assert.equal(bad.counts().calls,2);assert.equal(bad.counts().finalizations,0);});

test('location detour requires published knowledge evidence before finalization',async()=>{const snap={...snapshot,messages:[{...snapshot.messages[0],contentText:'زين وين موقعكم؟'}]};const f=fixture([final,{type:'tool_request',toolName:'searchKnowledge',arguments:{query:'location'}},final]);const r=await runAgentOrchestrator(snap,f);assert.equal(r.terminal,'SUCCEEDED');assert.equal(f.counts().calls,3);assert.equal(f.counts().executions,1);assert.equal(f.counts().mutations,0);});
