import { BusinessPackDefinition } from '@ai-sales-agent/contracts';

export const CLINIC_PACK: BusinessPackDefinition = {
  id: 'CLINIC',
  version: 'clinic.v1',
  name: 'Clinic / Healthcare Practice',
  description: 'Tailored for medical, dental, and wellness clinics providing appointments, patient registration, and consultation services.',
  category: 'Healthcare & Wellness',
  recommendedCapabilities: {
    supportsBooking: true,
    supportsServices: true,
    supportsStaff: true,
    supportsLocations: true,
    supportsLeads: true,
    leadRequiredBeforeBooking: false,
    autoCreateLeadOnIntent: true,
    supportsOffers: true,
    supportsQuotes: false,
    supportsOrders: false,
    supportsProducts: false,
    supportsListings: false,
  },
  onboardingDefaults: {
    defaultLanguage: 'ar',
    defaultCurrency: 'IQD',
    timezone: 'Asia/Baghdad',
  },
  conversationProfileDefaults: {
    tone: 'PROFESSIONAL',
    formality: 'BALANCED',
    salesStyle: 'LOW_PRESSURE',
    greetingStyle: 'WARM',
    handoffStyle: 'PROFESSIONAL',
    emojiUsage: 'MINIMAL',
    responseLength: 'BALANCED',
    dialect: 'IRAQI',
  },
  policyTemplates: [
    {
      starterKey: 'clinic.policy.cancellation.default',
      policyType: 'CANCELLATION',
      title: 'Standard Clinic Cancellation Policy',
      summary: 'Appointments can be cancelled up to 24 hours prior without fee.',
      rulesJson: {
        cutoffMinutes: 1440,
        allowAfterCutoff: true,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
    {
      starterKey: 'clinic.policy.rescheduling.default',
      policyType: 'RESCHEDULING',
      title: 'Clinic Rescheduling Policy',
      summary: 'Rescheduling requires at least 12 hours advance notice.',
      rulesJson: {
        cutoffMinutes: 720,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
    {
      starterKey: 'clinic.policy.payment.default',
      policyType: 'PAYMENT',
      title: 'Clinic Accepted Payment Methods',
      summary: 'Payment accepted via Cash and Cards at the clinic.',
      rulesJson: {
        acceptedMethods: ['Cash', 'Credit/Debit Card'],
      },
      enforcementMode: 'INFORMATIONAL_ONLY',
      status: 'DRAFT',
    },
  ],
  knowledgeStarters: [
    {
      starterKey: 'clinic.knowledge.preparation',
      title: 'Patient Visit Preparation & Checklist',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'Please arrive 10 minutes prior to your scheduled appointment. Bring any relevant previous medical records and identification.',
      status: 'DRAFT',
    },
    {
      starterKey: 'clinic.knowledge.location_parking',
      title: 'Clinic Location, Access & Parking Info',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'Free visitor parking is available on-site. The clinic entrance is wheelchair accessible on the ground floor.',
      status: 'DRAFT',
    },
    {
      starterKey: 'clinic.knowledge.insurance_payment',
      title: 'Insurance & Payment Guidance',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'We accept major medical insurance plans for eligible treatments. Please confirm your coverage with our reception team before your visit.',
      status: 'DRAFT',
    },
  ],
  catalogStarters: [
    {
      starterKey: 'clinic.catalog.general_consultation',
      kind: 'SERVICE',
      name: 'General Consultation & Initial Assessment',
      description: 'Comprehensive clinical examination, health history review, and personalized care plan.',
      status: 'INACTIVE',
      amountMinor: null,
      currency: 'IQD',
      needsReview: true,
    },
  ],
  metadata: {
    recommendedIcon: 'Stethoscope',
    targetIndustries: ['Dental', 'General Practice', 'Dermatology', 'Physiotherapy'],
  },
};

export const SALON_PACK: BusinessPackDefinition = {
  id: 'SALON',
  version: 'salon.v1',
  name: 'Salon / Beauty & Spa',
  description: 'Configured for hair salons, aesthetic centers, and wellness spas with specialist staff bookings and service menus.',
  category: 'Beauty & Personal Care',
  recommendedCapabilities: {
    supportsBooking: true,
    supportsServices: true,
    supportsStaff: true,
    supportsLocations: true,
    supportsLeads: true,
    leadRequiredBeforeBooking: false,
    autoCreateLeadOnIntent: false,
    supportsOffers: true,
    supportsQuotes: false,
    supportsOrders: false,
    supportsProducts: false,
    supportsListings: false,
  },
  onboardingDefaults: {
    defaultLanguage: 'ar',
    defaultCurrency: 'IQD',
    timezone: 'Asia/Baghdad',
  },
  conversationProfileDefaults: {
    tone: 'FRIENDLY',
    formality: 'CASUAL',
    responseLength: 'BALANCED',
    salesStyle: 'BALANCED',
    emojiUsage: 'NORMAL',
    greetingStyle: 'WARM',
    handoffStyle: 'WARM',
    dialect: 'IRAQI',
  },
  policyTemplates: [
    {
      starterKey: 'salon.policy.cancellation.default',
      policyType: 'CANCELLATION',
      title: 'Salon Appointment Cancellation',
      summary: 'Please notify us at least 4 hours before your appointment for cancellations.',
      rulesJson: {
        cutoffMinutes: 240,
        allowAfterCutoff: true,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
    {
      starterKey: 'salon.policy.rescheduling.default',
      policyType: 'RESCHEDULING',
      title: 'Salon Rescheduling Notice',
      summary: 'Rescheduling is permitted up to 2 hours before the appointment.',
      rulesJson: {
        cutoffMinutes: 120,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
  ],
  knowledgeStarters: [
    {
      starterKey: 'salon.knowledge.service_prep',
      title: 'Hair & Skin Treatment Preparation Guide',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'For coloring or chemical treatments, please arrive with clean, dry hair. For facials, avoid heavy makeup before your visit.',
      status: 'DRAFT',
    },
    {
      starterKey: 'salon.knowledge.aftercare',
      title: 'General Post-Treatment Aftercare Tips',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'To maintain best results, follow our stylist recommendations and use sulfate-free products.',
      status: 'DRAFT',
    },
  ],
  catalogStarters: [
    {
      starterKey: 'salon.catalog.hair_styling',
      kind: 'SERVICE',
      name: 'Signature Haircut & Styling Session',
      description: 'Personal consultation, wash, precision cut, and styling.',
      status: 'INACTIVE',
      amountMinor: null,
      currency: 'IQD',
      needsReview: true,
    },
  ],
  metadata: {
    recommendedIcon: 'Sparkles',
    targetIndustries: ['Hair Salon', 'Nail Studio', 'Spa & Wellness', 'Barbershop'],
  },
};

export const REAL_ESTATE_PACK: BusinessPackDefinition = {
  id: 'REAL_ESTATE',
  version: 'real_estate.v1',
  name: 'Real Estate / Property Agency',
  description: 'Optimized for real estate brokerages and property managers handling buyer/renter inquiries, viewing appointments, and listings.',
  category: 'Real Estate & Property',
  recommendedCapabilities: {
    supportsBooking: false,
    supportsServices: false,
    supportsListings: true,
    supportsLeads: true,
    autoCreateLeadOnIntent: true,
    leadRequiredBeforeBooking: false,
    supportsOffers: true,
    supportsQuotes: true,
    supportsStaff: true,
    supportsLocations: true,
    supportsOrders: false,
    supportsProducts: false,
  },
  onboardingDefaults: {
    defaultLanguage: 'ar',
    defaultCurrency: 'USD',
    timezone: 'Asia/Baghdad',
  },
  conversationProfileDefaults: {
    tone: 'PROFESSIONAL',
    formality: 'FORMAL',
    responseLength: 'DETAILED',
    salesStyle: 'PROACTIVE',
    emojiUsage: 'MINIMAL',
    greetingStyle: 'FORMAL',
    handoffStyle: 'PROFESSIONAL',
    dialect: 'IRAQI',
  },
  policyTemplates: [
    {
      starterKey: 'real_estate.policy.service_area.default',
      policyType: 'SERVICE_AREA',
      title: 'Real Estate Operating Coverage',
      summary: 'We provide property brokerage and advisory across primary metropolitan areas.',
      rulesJson: {
        supportedAreas: ['Baghdad Central', 'Karkh', 'Rusafa'],
        excludedAreas: [],
      },
      enforcementMode: 'INFORMATIONAL_ONLY',
      status: 'DRAFT',
    },
  ],
  knowledgeStarters: [
    {
      starterKey: 'real_estate.knowledge.viewing_process',
      title: 'Property Viewing & Consultation Process',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'Property viewings are scheduled with dedicated agents. Please provide your preferred time, budget range, and desired property specifications.',
      status: 'DRAFT',
    },
    {
      starterKey: 'real_estate.knowledge.documentation',
      title: 'Required Purchase & Lease Documentation',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'Standard transactions require valid government identification, proof of funds or pre-approval, and signed brokerage agreements.',
      status: 'DRAFT',
    },
  ],
  catalogStarters: [
    {
      starterKey: 'real_estate.catalog.featured_residential',
      kind: 'LISTING',
      name: 'Featured Residential Property Showcase',
      description: 'Premium residential listing available for viewing and consultation.',
      status: 'INACTIVE',
      amountMinor: null,
      currency: 'USD',
      needsReview: true,
    },
  ],
  metadata: {
    recommendedIcon: 'Building',
    targetIndustries: ['Residential Brokerage', 'Commercial Real Estate', 'Property Management'],
  },
};

export const RESTAURANT_PACK: BusinessPackDefinition = {
  id: 'RESTAURANT',
  version: 'restaurant.v1',
  name: 'Restaurant / Food & Dining',
  description: 'Designed for restaurants, cafes, and dining venues taking table reservations, group bookings, and food inquiries.',
  category: 'Food & Hospitality',
  recommendedCapabilities: {
    supportsBooking: true,
    supportsServices: true,
    supportsProducts: true,
    supportsOffers: true,
    supportsStaff: false,
    supportsLocations: true,
    supportsLeads: true,
    autoCreateLeadOnIntent: false,
    leadRequiredBeforeBooking: false,
    supportsQuotes: false,
    supportsOrders: false,
    supportsListings: false,
  },
  onboardingDefaults: {
    defaultLanguage: 'ar',
    defaultCurrency: 'IQD',
    timezone: 'Asia/Baghdad',
  },
  conversationProfileDefaults: {
    tone: 'FRIENDLY',
    formality: 'CASUAL',
    responseLength: 'SHORT',
    salesStyle: 'BALANCED',
    emojiUsage: 'NORMAL',
    greetingStyle: 'WARM',
    handoffStyle: 'WARM',
    dialect: 'IRAQI',
  },
  policyTemplates: [
    {
      starterKey: 'restaurant.policy.cancellation.default',
      policyType: 'CANCELLATION',
      title: 'Table Reservation Cancellation Policy',
      summary: 'Table reservations can be cancelled up to 1 hour before scheduled arrival.',
      rulesJson: {
        cutoffMinutes: 60,
        allowAfterCutoff: true,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
    {
      starterKey: 'restaurant.policy.advance_notice.default',
      policyType: 'ADVANCE_NOTICE',
      title: 'Advance Reservation Requirements',
      summary: 'Reservations require at least 30 minutes advance notice.',
      rulesJson: {
        minimumLeadMinutes: 30,
        maximumAdvanceDays: 14,
      },
      enforcementMode: 'INFORMATIONAL_ONLY',
      status: 'DRAFT',
    },
  ],
  knowledgeStarters: [
    {
      starterKey: 'restaurant.knowledge.dining_experience',
      title: 'Dining Experience, Seating & Dietary Options',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'We offer indoor and outdoor family seating. Vegetarian, vegan, and gluten-free dietary options are available upon request.',
      status: 'DRAFT',
    },
    {
      starterKey: 'restaurant.knowledge.parking_hours',
      title: 'Opening Hours & Valet Parking',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'Open daily from 12:00 PM to 12:00 AM. Complimentary valet parking is available at the front entrance.',
      status: 'DRAFT',
    },
  ],
  catalogStarters: [
    {
      starterKey: 'restaurant.catalog.table_reservation',
      kind: 'SERVICE',
      name: 'Dining Table Reservation (Standard / Family)',
      description: 'Reserved table seating for parties of 1 to 8 guests.',
      status: 'INACTIVE',
      amountMinor: null,
      currency: 'IQD',
      needsReview: true,
    },
  ],
  metadata: {
    recommendedIcon: 'Utensils',
    targetIndustries: ['Fine Dining', 'Casual Restaurant', 'Cafe & Bistro', 'Catering'],
  },
};

export const PROFESSIONAL_SERVICES_PACK: BusinessPackDefinition = {
  id: 'PROFESSIONAL_SERVICES',
  version: 'professional_services.v1',
  name: 'Professional Services & Advisory',
  description: 'Structured for legal, accounting, consulting, and engineering advisory firms managing client inquiries and high-value consultations.',
  category: 'Consulting & Advisory',
  recommendedCapabilities: {
    supportsBooking: true,
    supportsServices: true,
    supportsLeads: true,
    leadRequiredBeforeBooking: true,
    autoCreateLeadOnIntent: true,
    supportsOffers: false,
    supportsQuotes: true,
    supportsStaff: true,
    supportsLocations: true,
    supportsOrders: false,
    supportsProducts: false,
    supportsListings: false,
  },
  onboardingDefaults: {
    defaultLanguage: 'ar',
    defaultCurrency: 'USD',
    timezone: 'Asia/Baghdad',
  },
  conversationProfileDefaults: {
    tone: 'PROFESSIONAL',
    formality: 'FORMAL',
    responseLength: 'BALANCED',
    salesStyle: 'LOW_PRESSURE',
    emojiUsage: 'NEVER',
    greetingStyle: 'FORMAL',
    handoffStyle: 'PROFESSIONAL',
    dialect: 'IRAQI',
  },
  policyTemplates: [
    {
      starterKey: 'prof_services.policy.cancellation.default',
      policyType: 'CANCELLATION',
      title: 'Advisory Consultation Cancellation Policy',
      summary: 'Consultation bookings can be rescheduled or cancelled up to 24 hours in advance.',
      rulesJson: {
        cutoffMinutes: 1440,
        allowAfterCutoff: false,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
    {
      starterKey: 'prof_services.policy.rescheduling.default',
      policyType: 'RESCHEDULING',
      title: 'Advisory Rescheduling Policy',
      summary: 'Rescheduling requires at least 24 hours advance notice.',
      rulesJson: {
        cutoffMinutes: 1440,
      },
      enforcementMode: 'ENFORCEABLE',
      status: 'DRAFT',
    },
  ],
  knowledgeStarters: [
    {
      starterKey: 'prof_services.knowledge.consultation_scope',
      title: 'Client Advisory & Engagement Process',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'Our initial consultation includes a structured needs assessment, scope review, and tailored proposal formulation.',
      status: 'DRAFT',
    },
    {
      starterKey: 'prof_services.knowledge.confidentiality',
      title: 'Confidentiality & Non-Disclosure Commitment',
      sourceType: 'TEXT',
      visibility: 'CUSTOMER_VISIBLE',
      content: 'All client discussions, case notes, and proprietary data are protected under strict non-disclosure policies.',
      status: 'DRAFT',
    },
  ],
  catalogStarters: [
    {
      starterKey: 'prof_services.catalog.advisory_session',
      kind: 'SERVICE',
      name: 'Strategic Advisory Consultation',
      description: 'One-on-one executive advisory session with a senior practice consultant.',
      status: 'INACTIVE',
      amountMinor: null,
      currency: 'USD',
      needsReview: true,
    },
  ],
  metadata: {
    recommendedIcon: 'Briefcase',
    targetIndustries: ['Legal Firm', 'Accounting & Audit', 'Management Consulting', 'Architecture & Engineering'],
  },
};

export const REPRESENTATIVE_BUSINESS_PACKS: BusinessPackDefinition[] = [
  CLINIC_PACK,
  SALON_PACK,
  REAL_ESTATE_PACK,
  RESTAURANT_PACK,
  PROFESSIONAL_SERVICES_PACK,
];
