import type {
  AgentIntent,
  WorkflowDefinition,
  WorkflowId,
} from '@ai-sales-agent/contracts';

export const WORKFLOW_DEFINITIONS: Record<WorkflowId, WorkflowDefinition> = {
  DISCOVERY: {
    id: 'DISCOVERY',
    title: 'Service & Product Discovery',
    description: 'Find, explore, and check prices for catalog services and items',
    supportedIntents: ['DISCOVERY', 'CATALOG_INQUIRY', 'PRICE_INQUIRY'],
    requiredCapabilities: [],
    allowedTools: ['searchServices', 'getServiceDetails', 'getServicePrice'],
    mutationTools: [],
    isExecutable: true,
    interruptible: true,
  },
  LEAD_CAPTURE: {
    id: 'LEAD_CAPTURE',
    title: 'Lead Capture & Qualification',
    description: 'Capture, update, and qualify potential customer inquiries',
    supportedIntents: ['LEAD_INTENT'],
    requiredCapabilities: ['supportsLeads'],
    allowedTools: [
      'ensureLead',
      'updateLeadQualification',
      'getLead',
      'transitionLead',
      'getCustomer',
      'createCustomer',
      'searchServices',
    ],
    mutationTools: ['ensureLead', 'updateLeadQualification', 'transitionLead', 'createCustomer'],
    isExecutable: true,
    interruptible: true,
  },
  BOOKING: {
    id: 'BOOKING',
    title: 'Appointment Booking',
    description: 'Explore availability, hold candidate slots, and confirm appointments',
    supportedIntents: ['BOOKING_INTENT'],
    requiredCapabilities: ['supportsBooking'],
    allowedTools: [
      'searchServices',
      'getServiceDetails',
      'getServicePrice',
      'getAvailableSlots',
      'createBooking',
      'getBookings',
      'ensureLead',
      'getCustomer',
      'createCustomer',
    ],
    mutationTools: ['createBooking', 'ensureLead', 'createCustomer'],
    isExecutable: true,
    interruptible: true,
  },
  BOOKING_CANCELLATION: {
    id: 'BOOKING_CANCELLATION',
    title: 'Booking Cancellation',
    description: 'Cancel an existing confirmed booking according to cancellation policy cutoff',
    supportedIntents: ['BOOKING_CANCEL_INTENT'],
    requiredCapabilities: ['supportsBooking'],
    allowedTools: ['getBookings', 'cancelBooking', 'getEffectivePolicy'],
    mutationTools: ['cancelBooking'],
    isExecutable: true,
    interruptible: false,
  },
  BOOKING_RESCHEDULING: {
    id: 'BOOKING_RESCHEDULING',
    title: 'Booking Rescheduling',
    description: 'Reschedule an existing booking to a new candidate slot according to rescheduling policy cutoff',
    supportedIntents: ['BOOKING_RESCHEDULE_INTENT'],
    requiredCapabilities: ['supportsBooking'],
    allowedTools: ['getBookings', 'getAvailableSlots', 'rescheduleBooking', 'getEffectivePolicy'],
    mutationTools: ['rescheduleBooking'],
    isExecutable: true,
    interruptible: false,
  },
  OFFER_DISCOVERY: {
    id: 'OFFER_DISCOVERY',
    title: 'Active Offers & Promotions',
    description: 'Discover active discounts and promotional pricing',
    supportedIntents: ['OFFER_INQUIRY'],
    requiredCapabilities: ['supportsOffers'],
    allowedTools: ['getActiveOffers', 'searchServices', 'getServicePrice'],
    mutationTools: [],
    isExecutable: true,
    interruptible: true,
  },
  POLICY_LOOKUP: {
    id: 'POLICY_LOOKUP',
    title: 'Business Policy Lookup',
    description: 'Retrieve authoritative business policies (cancellation, privacy, payment, terms)',
    supportedIntents: ['POLICY_INQUIRY'],
    requiredCapabilities: [],
    allowedTools: ['getEffectivePolicy'],
    mutationTools: [],
    isExecutable: true,
    interruptible: true,
  },
  KNOWLEDGE_LOOKUP: {
    id: 'KNOWLEDGE_LOOKUP',
    title: 'Knowledge Base Search',
    description: 'Retrieve semantic knowledge articles and FAQs',
    supportedIntents: ['KNOWLEDGE_INQUIRY'],
    requiredCapabilities: [],
    allowedTools: ['searchKnowledge'],
    mutationTools: [],
    isExecutable: true,
    interruptible: true,
  },
  HUMAN_HANDOFF: {
    id: 'HUMAN_HANDOFF',
    title: 'Human Takeover Request',
    description: 'Transfer conversation control to a human operator',
    supportedIntents: ['HANDOFF_REQUEST', 'SUPPORT_REQUEST'],
    requiredCapabilities: [],
    allowedTools: ['handoffToHuman'],
    mutationTools: ['handoffToHuman'],
    isExecutable: true,
    interruptible: false,
  },
  GENERAL_SUPPORT: {
    id: 'GENERAL_SUPPORT',
    title: 'General Support & Inquiries',
    description: 'Handle general inquiries, follow-ups, and open-ended assistance',
    supportedIntents: ['GENERAL_INQUIRY', 'UNKNOWN', 'FOLLOW_UP_INTENT'],
    requiredCapabilities: [],
    allowedTools: [
      'searchServices',
      'getServiceDetails',
      'getActiveOffers',
      'getEffectivePolicy',
      'searchKnowledge',
      'getFollowUps',
    ],
    mutationTools: [],
    isExecutable: true,
    interruptible: true,
  },
  QUOTE: {
    id: 'QUOTE',
    title: 'Price Quote & Estimation',
    description: 'Formal price quote generation, presentation, and acceptance',
    supportedIntents: ['QUOTE_INTENT'],
    requiredCapabilities: ['supportsQuotes'],
    allowedTools: [
      'getQuote',
      'createQuote',
      'presentQuote',
      'acceptQuote',
      'rejectQuote',
      'cancelQuote',
      'searchServices',
      'getServiceDetails',
      'getActiveOffers',
      'getEffectivePolicy',
      'searchKnowledge',
    ],
    mutationTools: ['createQuote', 'presentQuote', 'acceptQuote', 'rejectQuote', 'cancelQuote'],
    isExecutable: true,
    interruptible: true,
  },
  PURCHASE: {
    id: 'PURCHASE',
    title: 'Order Placement & Purchase',
    description: 'Product and service order creation, confirmation, and cancellation',
    supportedIntents: ['PURCHASE_INTENT'],
    requiredCapabilities: ['supportsOrders'],
    allowedTools: [
      'getOrder',
      'createOrder',
      'confirmOrder',
      'cancelOrder',
      'searchServices',
      'getServiceDetails',
      'getActiveOffers',
      'getEffectivePolicy',
      'searchKnowledge',
    ],
    mutationTools: ['createOrder', 'confirmOrder', 'cancelOrder'],
    isExecutable: true,
    interruptible: true,
  },
};

export function getWorkflowDefinition(id: WorkflowId): WorkflowDefinition {
  const def = WORKFLOW_DEFINITIONS[id];
  if (!def) {
    throw new Error(`Unknown workflow ID: ${id}`);
  }
  return def;
}

export function findWorkflowForIntent(intent: AgentIntent): WorkflowDefinition | null {
  for (const def of Object.values(WORKFLOW_DEFINITIONS)) {
    if (def.supportedIntents.includes(intent)) {
      return def;
    }
  }
  return null;
}
