'use client';
import { useState } from 'react';
import { OperatorNav } from '@/components/OperatorNav';
type Payload={asOf:string;range:{from:string;to:string;timezone:string};leads:{currentStatus:Record<string,number>;created:number};conversion:{numerator:number;denominator:number;rate:number|null;limitations:string[]};bookings:{byCurrentState:Record<string,number>};followUps:{byStatus:Record<string,number>;limitations:string[]};conversations:{outboundByOrigin:Record<string,number>;handoffActions:Record<string,number>;responseLatencyMs:Array<{origin:string;median_ms:number;p90_ms:number;samples:number}>};delivery:{byCurrentState:Record<string,number>;limitations:string[]};agent:{runsByStatus:Record<string,number>;usage:{modelCalls:number;inputTokens:number|null;outputTokens:number|null;totalTokens:number;totalLatencyMs:number|null};toolCalls:Array<{toolName:string;resultCode:string;count:number}>};unavailable:Record<string,{limitations:string[]}>};
const iso=(d:Date)=>d.toISOString().slice(0,10);
export default function AnalyticsPage(){const now=new Date();const [org,setOrg]=useState('');const [from,setFrom]=useState(iso(new Date(now.getTime()-30*86400000)));const [to,setTo]=useState(iso(new Date(now.getTime()+86400000)));const [timezone,setTimezone]=useState('Asia/Baghdad');const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState('');
async function load(){setError('');const p=new URLSearchParams({from,to,timezone});const r=await fetch(`/api/backend/organizations/${org}/analytics/overview?${p}`,{cache:'no-store'});if(!r.ok){setError(`Analytics unavailable (${r.status})`);setData(null);return;}setData(await r.json() as Payload)}
return <main style={{fontFamily:'Georgia, serif',maxWidth:1100}}><OperatorNav current="/analytics"/><h1>Analytics</h1><p>Structured outcomes only. All ranges use <code>[from,to)</code>.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><input placeholder="Organization id" value={org} onChange={e=>setOrg(e.target.value)}/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><input value={timezone} onChange={e=>setTimezone(e.target.value)}/><button onClick={()=>void load()} disabled={!org}>Refresh</button></div>{error?<p style={{color:'#a00'}}>{error}</p>:null}{data?<><p style={{fontSize:13,color:'#666'}}>As of {data.asOf} · {data.range.timezone}</p><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><Card title="Leads created" value={data.leads.created}/><Card title="Direct booking conversion" value={data.conversion.rate===null?'No denominator':`${data.conversion.numerator} / ${data.conversion.denominator} = ${(data.conversion.rate*100).toFixed(1)}%`}/><Card title="Confirmed bookings" value={data.bookings.byCurrentState.CONFIRMED??0}/><Card title="Cancelled bookings" value={data.bookings.byCurrentState.CANCELLED??0}/><Card title="AI outbound" value={data.conversations.outboundByOrigin.AI??0}/><Card title="Operator outbound" value={data.conversations.outboundByOrigin.OPERATOR??0}/><Card title="Model calls" value={data.agent.usage.modelCalls}/><Card title="Total tokens" value={data.agent.usage.totalTokens}/></section><Details title="Lead state" value={data.leads.currentStatus}/><Details title="Follow-ups" value={data.followUps.byStatus}/><Details title="Delivery state" value={data.delivery.byCurrentState}/><Details title="Agent runs" value={data.agent.runsByStatus}/><Details title="Tool usage" value={data.agent.toolCalls}/><h2>Unavailable by design</h2><ul>{Object.entries(data.unavailable).map(([k,v])=><li key={k}>{k}: {v.limitations.join(', ')}</li>)}</ul></>:null}</main>}
function Card({title,value}:{title:string;value:string|number}){return <div style={{border:'1px solid #ddd',padding:14}}><div style={{fontSize:12,color:'#666'}}>{title}</div><strong style={{fontSize:20}}>{value}</strong></div>}
function Details({title,value}:{title:string;value:unknown}){return <section><h2>{title}</h2><pre style={{background:'#f6f6f6',padding:12,overflow:'auto'}}>{JSON.stringify(value,null,2)}</pre></section>}
