import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {createRequire} from 'node:module';
const {Harness,assert}=createRequire(import.meta.url)('./runtime.ts') as typeof import('./runtime.ts');
import {createToolExecutor} from '../../packages/agent-adapters/src/tool-executor.ts';
import {createPgRunStore} from '../../packages/agent-adapters/src/pg-run-store.ts';
import {toolCancelBooking} from '../../packages/agent-adapters/src/booking-tools.ts';
import {PrismaService} from '../../apps/api/src/database/prisma.service.ts';
import {TenantContextService} from '../../apps/api/src/database/tenant-context.service.ts';
import {CustomersService} from '../../apps/api/src/customers/customers.service.ts';
import {ConversationsService} from '../../apps/api/src/conversations/conversations.service.ts';
import {KnowledgeService} from '../../apps/api/src/knowledge/knowledge.service.ts';
import {QuotesService} from '../../apps/api/src/quotes/quotes.service.ts';
import {OrdersService} from '../../apps/api/src/orders/orders.service.ts';
const h=new Harness(),runtime=new pg.Pool({connectionString:process.env.DATABASE_URL});process.env.KNOWLEDGE_STORAGE_BACKEND='filesystem';process.env.NODE_ENV='development';
const prisma=new PrismaService({databaseUrl:process.env.DATABASE_URL} as any),tenants=new TenantContextService(prisma);
const a=randomUUID(),b=randomUUID(),user=randomUUID(),customer=randomUUID(),customerB=randomUUID(),channel=randomUUID(),identity=randomUUID(),conv=randomUUID(),service=randomUUID(),location=randomUUID(),staff=randomUUID(),booking=randomUUID(),quote=randomUUID(),order=randomUUID(),doc=randomUUID(),catalog=randomUUID();
async function main(){await h.preflight();await h.scenario('CROSS_TENANT_ADVERSARIAL',async()=>{
 try{
 await h.pool.query("INSERT INTO organizations(id,name) VALUES($1,'MB15B isolated A'),($2,'MB15B isolated B')",[a,b]);await h.pool.query("INSERT INTO users(id,auth_subject) VALUES($1,$2)",[user,`mb15b-${user}`]);await h.pool.query("INSERT INTO organization_members(organization_id,user_id,role,status) VALUES($1,$2,'OWNER','ACTIVE')",[b,user]);await h.pool.query("INSERT INTO organization_capabilities(organization_id,supports_quotes,supports_orders,supports_offers) VALUES($1,true,true,true)",[b]);
 await h.pool.query("INSERT INTO customers(id,organization_id,display_name) VALUES($1,$2,'A private customer'),($3,$4,'B synthetic')",[customer,a,customerB,b]);await h.pool.query("INSERT INTO locations(id,organization_id,name,timezone) VALUES($1,$2,'A','Asia/Baghdad')",[location,a]);await h.pool.query("INSERT INTO catalog_items(id,organization_id,kind,name,amount_minor,currency,status) VALUES($1,$2,'SERVICE','A private catalog',12345,'IQD','ACTIVE')",[catalog,a]);await h.pool.query("INSERT INTO services(id,organization_id,location_id,catalog_item_id,name,duration_minutes,amount_minor,currency) VALUES($1,$2,$3,$4,'A private service',30,12345,'IQD')",[service,a,location,catalog]);await h.pool.query("INSERT INTO staff_members(id,organization_id,location_id,display_name) VALUES($1,$2,$3,'A private staff')",[staff,a,location]);
 await h.pool.query("INSERT INTO bookings(id,organization_id,customer_id,service_id,location_id,staff_member_id,starts_at,ends_at,occupied_starts_at,occupied_ends_at,timezone,duration_minutes,created_by_type) VALUES($1,$2,$3,$4,$5,$6,now()+interval '10 days',now()+interval '10 days 30 minutes',now()+interval '10 days',now()+interval '10 days 30 minutes','Asia/Baghdad',30,'USER')",[booking,a,customer,service,location,staff]);await h.pool.query("INSERT INTO quotes(id,organization_id,customer_id,status,currency) VALUES($1,$2,$3,'DRAFT','IQD')",[quote,a,customer]);await h.pool.query("INSERT INTO orders(id,organization_id,customer_id,status,currency) VALUES($1,$2,$3,'DRAFT','IQD')",[order,a,customer]);await h.pool.query("INSERT INTO knowledge_documents(id,organization_id,title) VALUES($1,$2,'A private source')",[doc,a]);
 await h.pool.query("INSERT INTO channel_connections(id,organization_id,provider,external_channel_id,status) VALUES($1,$2,'whatsapp',$3,'ACTIVE')",[channel,a,`mb15b-${channel}`]);await h.pool.query("INSERT INTO customer_identities(id,organization_id,customer_id,channel_connection_id,channel,external_address) VALUES($1,$2,$3,$4,'whatsapp',$5)",[identity,a,customer,channel,`synthetic-${identity}`]);await h.pool.query("INSERT INTO conversations(id,organization_id,customer_id,channel_connection_id,identity_id,mode) VALUES($1,$2,$3,$4,$5,'AI_PAUSED')",[conv,a,customer,channel,identity]);
 const c=await runtime.connect();try{await c.query('BEGIN');assert((await c.query('SELECT current_user')).rows[0].current_user==='app_runtime','rls_test_owner_bypass');await c.query("SELECT set_config('app.current_organization_id',$1,true)",[b]);await c.query("SELECT set_config('app.current_user_id',$1,true)",[user]);for(const [table,id]of [['customers',customer],['catalog_items',catalog],['services',service],['bookings',booking],['quotes',quote],['orders',order],['knowledge_documents',doc],['conversations',conv]])assert(!(await c.query(`SELECT id FROM ${table} WHERE id=$1`,[id])).rowCount,`cross_tenant_read_${table}`);
 const canceled=await toolCancelBooking(c as any,b,customerB,{bookingId:booking,expectedVersion:1},{agentRunId:randomUUID()});assert(!canceled.ok,'foreign_booking_canceled');await c.query('ROLLBACK');}finally{c.release();}
 const executor=createToolExecutor(runtime as any,createPgRunStore(runtime as any));const ctx={organizationId:b,customerId:customerB,conversationId:randomUUID(),agentRunId:randomUUID(),runKey:'mb15b-negative',leaseOwner:'synthetic',leaseFence:1,ownershipEpoch:1,targetIngressSequence:1,toolCallOrdinal:1,sandbox:false};const toolResults=[];
 for(const [name,args,customerId] of [['getServicePrice',{serviceId:service},customerB],['getActiveOffers',{catalogItemId:catalog},customerB],['getCustomer',{},customer],['getQuote',{quoteId:quote},customerB],['getOrder',{orderId:order},customerB]] as const){const r=await executor.execute(name,args,{...ctx,customerId});assert(!r.ok,`foreign_tool_${name}_returned_data`);toolResults.push({name,code:r.code});}
 const actor={userId:user,authSubject:`mb15b-${user}`};const checks=[()=>new CustomersService(tenants).get(actor,b,customer),()=>new ConversationsService(tenants,{} as any).getOne(actor,b,conv),()=>new KnowledgeService(tenants).getDocument(actor,b,doc),()=>new QuotesService(tenants).getQuote(actor,b,quote),()=>new OrdersService(tenants).getOrder(actor,b,order)];for(const check of checks){let status=0;try{await check();}catch(e){status=(e as any).getStatus?.()??0;}assert(status===404,'foreign_endpoint_service_not_404');}
 assert((await h.pool.query('SELECT status FROM bookings WHERE id=$1',[booking])).rows[0].status==='CONFIRMED','foreign_booking_changed');return {tenantA:a,tenantB:b,runtimeRole:'app_runtime',rlsNegativeCases:8,toolResults,endpointService404Cases:5,foreignBookingUnchanged:true};
 }finally{for(const table of ['conversations','customer_identities','channel_connections','bookings','quotes','orders','knowledge_documents','services','catalog_items','staff_members','locations','customers','organization_capabilities','organization_members'])await h.pool.query(`DELETE FROM ${table} WHERE organization_id=ANY($1::uuid[])`,[[a,b]]);await h.pool.query('DELETE FROM organizations WHERE id=ANY($1::uuid[])',[[a,b]]);await h.pool.query('DELETE FROM users WHERE id=$1',[user]);}
 });}
main().catch(()=>{h.scenarios.HARNESS={status:'FAIL',reason:'tenant_harness_failed'};h.save();process.exitCode=1;}).finally(async()=>{await runtime.end();await prisma.onModuleDestroy();await h.close();});
