import {execFileSync} from 'node:child_process';
import {Harness,assert,delay} from './runtime.ts';
const h=new Harness();
const docker=(...args:string[])=>execFileSync('docker',args,{encoding:'utf8',stdio:['ignore','pipe','ignore']});
async function observed(message:any,kind:string){const until=Date.now()+180000;while(Date.now()<until){const ar=(await h.pool.query(`SELECT ar.id,ar.status,(SELECT count(*)::int FROM tool_calls tc WHERE tc.agent_run_id=ar.id) tool_count,(SELECT count(*)::int FROM bookings b WHERE b.created_by_agent_run_id=ar.id) booking_count,(SELECT count(*)::int FROM outbound_attempts oa JOIN messages m ON m.id=oa.message_id WHERE m.conversation_id=ar.conversation_id) attempts FROM agent_runs ar WHERE ar.conversation_id=$1 AND ar.target_ingress_sequence=$2 ORDER BY ar.started_at DESC LIMIT 1`,[message.conversation_id,message.ingress_sequence])).rows[0];if(kind==='dispatch'&&ar){const received=await fetch('http://127.0.0.1:3415/simulator/messages').then(r=>r.json()) as any;if(received.messages.some((x:any)=>x.body?.to===message.phone))return {...ar,simulatorAcceptedBeforeKill:true};}if(ar&&((kind==='before-tool'&&ar.status==='RUNNING'&&ar.tool_count===0)||(kind==='after-read'&&ar.status==='RUNNING'&&ar.tool_count>0)||(kind==='after-mutation'&&ar.status==='RUNNING'&&ar.booking_count===1)||(kind==='dispatch'&&ar.attempts>0)))return ar;await delay(50);}throw new Error(`boundary_not_observed_${kind}`);}
async function main(){await h.preflight();for(const service of ['ai-sales-demo-worker','ai-sales-demo-redis','ai-sales-demo-postgres'])assert(docker('inspect','--format','{{ index .Config.Labels "com.docker.compose.project" }}',service).trim()==='ai-sales-demo','not_isolated_demo_container');const group=process.argv[2]??'all';
 if(['all','worker'].includes(group)){
 let passed=0;for(const kind of (process.argv[3]?[process.argv[3]]:['before-tool','after-read','after-mutation','dispatch']))await h.scenario(`WORKER_CRASH_${kind}`,async()=>{
  const p=h.phone();let m:any;let mutationBefore=0;
  if(kind==='after-mutation'){const t=await h.turn(p,`أريد حجز خدمة ${h.service.name} بتاريخ ${h.date}، اعرض المواعيد المتاحة`);h.success(t,['getAvailableSlots']);mutationBefore=(await h.mutations(t.conversationId)).bookings;m=await h.inbound(p,'تمام احجزلي أول موعد');}
  else {if(kind==='dispatch')await fetch('http://127.0.0.1:3415/simulator/scenario',{method:'POST',body:JSON.stringify({scenario:'TIMEOUT_AFTER_ACCEPT'})});m=await h.inbound(p,kind==='before-tool'?'ما هي سياسة الإلغاء؟':`شكد سعر خدمة ${h.service.name}؟`);}
  const boundary=await observed(m,kind);h.evidence.push({event:'crash_boundary_observed',kind,runId:h.runId,inboundId:m.providerInboundId,conversationId:m.conversation_id,...boundary});h.save();
  docker('kill','--signal','KILL','ai-sales-demo-worker');await delay(2000);docker('start','ai-sales-demo-worker');
  try{
   if(kind==='dispatch'){await fetch('http://127.0.0.1:3415/simulator/scenario',{method:'POST',body:JSON.stringify({scenario:'SUCCESS'})});const until=Date.now()+420000;while(Date.now()<until){const row=(await h.pool.query("SELECT delivery_state FROM messages WHERE conversation_id=$1 AND direction='OUTBOUND'",[m.conversation_id])).rows[0];if(row&&['UNKNOWN','ACCEPTED','DELIVERED','READ'].includes(row.delivery_state))break;await delay(500);}const states=(await h.pool.query('SELECT m.delivery_state,(SELECT count(*)::int FROM outbound_attempts a WHERE a.message_id=m.id) attempt_count FROM messages m WHERE m.conversation_id=$1 AND direction=$2',[m.conversation_id,'OUTBOUND'])).rows;h.evidence.push({event:'dispatch_recovery_state',conversationId:m.conversation_id,states});h.save();assert(states.length===1,'crash_duplicate_outbound');const received=await fetch('http://127.0.0.1:3415/simulator/messages').then(r=>r.json()) as any;assert(received.messages.filter((x:any)=>x.body?.to===p).length===1,'simulator_duplicate_acceptance');assert(states[0].attempt_count===1,'ambiguous_dispatch_retried');assert(['UNKNOWN','ACCEPTED','DELIVERED','READ'].includes(states[0].delivery_state),'dispatch_unresolved_state');}
   else {const t=await h.settle(m,420000);h.success(t);if(kind==='after-mutation')assert((await h.mutations(t.conversationId)).bookings-mutationBefore===1,'crash_duplicate_booking');}
   assert(!(await h.pool.query("SELECT 1 FROM agent_runs WHERE conversation_id=$1 AND status='RUNNING'",[m.conversation_id])).rowCount,'permanently_running_after_crash');passed++;return {kind,conversationId:m.conversation_id,observedAgentRunId:boundary.id};
  }finally{docker('start','ai-sales-demo-worker');await fetch('http://127.0.0.1:3415/simulator/scenario',{method:'POST',body:JSON.stringify({scenario:'SUCCESS'})});}
 });h.scenarios[process.argv[3]?'WORKER_CRASH_TARGETED':'WORKER_CRASH_RECOVERY']={status:passed===(process.argv[3]?1:4)?'PASS':'FAIL',variantsPassed:passed,coverage:process.argv[3]?[process.argv[3]]:['before-tool','after-read','after-mutation','dispatch']};h.save();
 }
 if(['all','redis'].includes(group))await h.scenario('REDIS_TEMPORARY_FAILURE',async()=>{const p=h.phone();let m:any;docker('pause','ai-sales-demo-redis');try{m=await h.inbound(p,'عندكم عروض حالياً؟');const pending=(await h.pool.query("SELECT count(*)::int n FROM outbox_events WHERE organization_id=$1 AND publication_status<>'PUBLISHED'",[h.org])).rows[0].n;assert(pending>0,'redis_outage_not_observable_in_outbox');await delay(5000);}finally{docker('unpause','ai-sales-demo-redis');}const t=await h.settle(m);h.success(t,['getActiveOffers']);assert((await h.pool.query('SELECT count(*)::int n FROM agent_runs WHERE conversation_id=$1 AND target_ingress_sequence=$2',[t.conversationId,t.ingressSequence])).rows[0].n===1,'redis_duplicate_processing');return {conversationId:t.conversationId,interruptionMs:5000};});
 if(['all','database'].includes(group)){
 let passed=0;for(const boundary of ['before-persistence','between-read-and-tool','before-outbound-persistence'])await h.scenario(`DATABASE_${boundary}`,async()=>{
 const p=h.phone();let pending:Promise<any>;let m:any;
 if(boundary==='before-persistence'){docker('pause','ai-sales-demo-postgres');try{pending=h.inbound(p,'عندكم عروض حالياً؟');await delay(2500);}finally{docker('unpause','ai-sales-demo-postgres');}m=await pending!;}
 else {m=await h.inbound(p,`شكد سعر خدمة ${h.service.name}؟`);await observed(m,boundary==='between-read-and-tool'?'before-tool':'after-read');docker('pause','ai-sales-demo-postgres');try{await delay(2500);}finally{docker('unpause','ai-sales-demo-postgres');}}
 const t=await h.settle(m);h.success(t);assert(t.mutationsAfter.bookings===t.mutationsBefore.bookings,'db_partial_mutation');assert((await h.pool.query('SELECT count(*)::int n FROM messages WHERE provider_message_id=$1 AND organization_id=$2',[t.inboundId,h.org])).rows[0].n===1,'db_duplicate_persistence');passed++;return {boundary,conversationId:t.conversationId,interruptionMs:2500};
 });h.scenarios.DATABASE_TEMPORARY_FAILURE={status:passed===3?'PASS':'FAIL',variantsPassed:passed};h.save();
 }
}
main().catch(e=>{h.scenarios.HARNESS={status:'FAIL',reason:e.message};h.save();console.error('INFRASTRUCTURE_CHAOS_FAILED');process.exitCode=1;}).finally(async()=>{for(const service of ['ai-sales-demo-redis','ai-sales-demo-postgres'])try{docker('unpause',service);}catch{}try{docker('start','ai-sales-demo-worker');}catch{}await h.close();});
